### ISSUE TITLE
Strange record size limits

### ISSUE THREAD

**Issue by 9teen90nine** [solarwinds/fluent-plugin-papertrail#17]
I just ran this plugin for our setup and found out two undocumented limits:
1. Tag size is limited to 32 symbols - if tag is longer (which is true for us) then the plugin will throw an error;
2. It seems to me that the message field is truncated to 969 symbols.
Is that a limitation or am I missing something?

**Comment by kyleroot** [comment]
I also ran into these limits, I believe they both can be traced to the RFC for syslog. Tags cannot exceed 32 characters and a syslog message has a total size limit of 1KiB.

Our previous log shipper however was able to send larger messages to Papertrail so I am suspecting it used non-standard extensions to syslog to accomplish this. The 1KiB limit in this plugin makes it unusable for my purposes.

**Comment by kyleroot** [comment]
I found the source of the 1KiB limit, it is within the syslog library used.

https://github.com/eric/syslog_protocol/blob/master/lib/syslog_protocol/packet.rb#L10

**Comment by kyleroot** [comment]
https://github.com/papertrail/remote_syslog2/blob/master/syslog/syslog.go#L195

Papertrail's own remote_syslog2 daemon allows the maximum syslog packet size be dynamically set though it has a default value of 99990.

https://github.com/papertrail/remote_syslog2/blob/2e1564aab31cbd679833d39c04078e127082f74f/config.go#L82

Since this plugin is intended to interface only with Papertrail we can safely increase this limit to that value.

**Comment by cmrust** [comment]
Thanks for referencing Papertrail's default in remote_syslog2 and for the PR @kyleroot. This has been merged and released to rubygems as `0.2.6`.
